
public interface MetaProcessor {
	/**
	 * @return true if new code generated by this processor
	 */
	protected boolean process(Context ctx);

	public static class Context {
		List<Element> elements;
		MetacodeContext metac;
		JavaWriver out; // sub writers? what if close or smthng
		roundEnv;
	}

}
